// World statistics data for the monitor dashboard
// Values are approximate daily rates used for live counter animation

export interface WorldStat {
  id: string;
  label: string;
  labelTh: string;
  baseValue: number;
  ratePerSecond: number; // change per second (positive = increase, negative = decrease)
  unit: string;
  format: "number" | "compact";
  color: string;
}

export interface StatCategory {
  id: string;
  title: string;
  titleTh: string;
  icon: string;
  color: string;
  bgColor: string;
  stats: WorldStat[];
}

export const worldCategories: StatCategory[] = [
  {
    id: "population",
    title: "World Population",
    titleTh: "ประชากรโลก",
    icon: "Users",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10 border-blue-500/20",
    stats: [
      {
        id: "world-population",
        label: "Current World Population",
        labelTh: "ประชากรโลกปัจจุบัน",
        baseValue: 8_119_000_000,
        ratePerSecond: 2.5,
        unit: "",
        format: "number",
        color: "text-blue-400",
      },
      {
        id: "births-today",
        label: "Births Today",
        labelTh: "เกิดวันนี้",
        baseValue: 0,
        ratePerSecond: 4.4,
        unit: "",
        format: "number",
        color: "text-green-400",
      },
      {
        id: "deaths-today",
        label: "Deaths Today",
        labelTh: "เสียชีวิตวันนี้",
        baseValue: 0,
        ratePerSecond: 1.8,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
      {
        id: "net-growth-today",
        label: "Net Population Growth Today",
        labelTh: "ประชากรเพิ่มสุทธิวันนี้",
        baseValue: 0,
        ratePerSecond: 2.6,
        unit: "",
        format: "number",
        color: "text-emerald-400",
      },
    ],
  },
  {
    id: "government-economics",
    title: "Government & Economics",
    titleTh: "รัฐบาลและเศรษฐกิจ",
    icon: "Landmark",
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10 border-yellow-500/20",
    stats: [
      {
        id: "public-healthcare-expenditure",
        label: "Public Healthcare Expenditure Today",
        labelTh: "ค่าใช้จ่ายด้านสุขภาพวันนี้",
        baseValue: 0,
        ratePerSecond: 289_351,
        unit: "$",
        format: "number",
        color: "text-yellow-400",
      },
      {
        id: "public-education-expenditure",
        label: "Public Education Expenditure Today",
        labelTh: "ค่าใช้จ่ายด้านการศึกษาวันนี้",
        baseValue: 0,
        ratePerSecond: 173_611,
        unit: "$",
        format: "number",
        color: "text-amber-400",
      },
      {
        id: "public-military-expenditure",
        label: "Public Military Expenditure Today",
        labelTh: "ค่าใช้จ่ายด้านกองทัพวันนี้",
        baseValue: 0,
        ratePerSecond: 69_444,
        unit: "$",
        format: "number",
        color: "text-orange-400",
      },
    ],
  },
  {
    id: "society-media",
    title: "Society & Media",
    titleTh: "สังคมและสื่อ",
    icon: "Newspaper",
    color: "text-purple-400",
    bgColor: "bg-purple-500/10 border-purple-500/20",
    stats: [
      {
        id: "emails-sent",
        label: "Emails Sent Today",
        labelTh: "อีเมลที่ส่งวันนี้",
        baseValue: 0,
        ratePerSecond: 3_819_444,
        unit: "",
        format: "number",
        color: "text-purple-400",
      },
      {
        id: "blog-posts",
        label: "Blog Posts Written Today",
        labelTh: "บล็อกโพสต์วันนี้",
        baseValue: 0,
        ratePerSecond: 69.4,
        unit: "",
        format: "number",
        color: "text-violet-400",
      },
      {
        id: "tweets-sent",
        label: "Tweets Sent Today",
        labelTh: "ทวีตวันนี้",
        baseValue: 0,
        ratePerSecond: 6_944,
        unit: "",
        format: "number",
        color: "text-sky-400",
      },
      {
        id: "google-searches",
        label: "Google Searches Today",
        labelTh: "ค้นหา Google วันนี้",
        baseValue: 0,
        ratePerSecond: 108_507,
        unit: "",
        format: "number",
        color: "text-blue-400",
      },
    ],
  },
  {
    id: "environment",
    title: "Environment",
    titleTh: "สิ่งแวดล้อม",
    icon: "TreePine",
    color: "text-green-400",
    bgColor: "bg-green-500/10 border-green-500/20",
    stats: [
      {
        id: "co2-emissions",
        label: "CO₂ Emissions (tons)",
        labelTh: "ปล่อย CO₂ วันนี้ (ตัน)",
        baseValue: 0,
        ratePerSecond: 1_186,
        unit: "",
        format: "number",
        color: "text-orange-400",
      },
      {
        id: "forest-loss",
        label: "Forest Lost (hectares)",
        labelTh: "พื้นที่ป่าหาย (เฮกตาร์)",
        baseValue: 0,
        ratePerSecond: 1.42,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
      {
        id: "desertification",
        label: "Desertification (hectares)",
        labelTh: "กลายเป็นทะเลทราย (เฮกตาร์)",
        baseValue: 0,
        ratePerSecond: 0.38,
        unit: "",
        format: "number",
        color: "text-yellow-400",
      },
      {
        id: "toxic-chemicals",
        label: "Toxic Chemicals Released (tons)",
        labelTh: "สารพิษปล่อยสู่สิ่งแวดล้อม (ตัน)",
        baseValue: 0,
        ratePerSecond: 0.253,
        unit: "",
        format: "number",
        color: "text-rose-400",
      },
    ],
  },
  {
    id: "food",
    title: "Food",
    titleTh: "อาหาร",
    icon: "Wheat",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10 border-amber-500/20",
    stats: [
      {
        id: "undernourished",
        label: "Undernourished People",
        labelTh: "ผู้ขาดสารอาหาร",
        baseValue: 820_000_000,
        ratePerSecond: 0,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
      {
        id: "overweight",
        label: "Overweight People",
        labelTh: "ผู้มีน้ำหนักเกิน",
        baseValue: 1_950_000_000,
        ratePerSecond: 0,
        unit: "",
        format: "number",
        color: "text-amber-400",
      },
      {
        id: "food-produced",
        label: "Food Produced Today (tons)",
        labelTh: "อาหารที่ผลิตวันนี้ (ตัน)",
        baseValue: 0,
        ratePerSecond: 11_574,
        unit: "",
        format: "number",
        color: "text-green-400",
      },
    ],
  },
  {
    id: "energy",
    title: "Energy",
    titleTh: "พลังงาน",
    icon: "Zap",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10 border-cyan-500/20",
    stats: [
      {
        id: "energy-used",
        label: "Energy Used Today (MWh)",
        labelTh: "พลังงานที่ใช้วันนี้ (MWh)",
        baseValue: 0,
        ratePerSecond: 68_287,
        unit: "",
        format: "number",
        color: "text-cyan-400",
      },
      {
        id: "solar-energy",
        label: "Solar Energy (MWh)",
        labelTh: "พลังงานแสงอาทิตย์ (MWh)",
        baseValue: 0,
        ratePerSecond: 3_472,
        unit: "",
        format: "number",
        color: "text-yellow-400",
      },
      {
        id: "oil-pumped",
        label: "Oil Pumped Today (barrels)",
        labelTh: "น้ำมันสูบวันนี้ (บาร์เรล)",
        baseValue: 0,
        ratePerSecond: 1_140,
        unit: "",
        format: "number",
        color: "text-stone-400",
      },
      {
        id: "days-to-oil-end",
        label: "Days to End of Oil",
        labelTh: "วันก่อนน้ำมันหมด",
        baseValue: 15_327,
        ratePerSecond: 0,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
    ],
  },
  {
    id: "health",
    title: "Health",
    titleTh: "สุขภาพ",
    icon: "Heart",
    color: "text-rose-400",
    bgColor: "bg-rose-500/10 border-rose-500/20",
    stats: [
      {
        id: "communicable-disease-deaths",
        label: "Communicable Disease Deaths Today",
        labelTh: "เสียชีวิตจากโรคติดต่อวันนี้",
        baseValue: 0,
        ratePerSecond: 0.45,
        unit: "",
        format: "number",
        color: "text-rose-400",
      },
      {
        id: "seasonal-flu-deaths",
        label: "Seasonal Flu Deaths This Year",
        labelTh: "เสียชีวิตจากไข้หวัดใหญ่ปีนี้",
        baseValue: 128_000,
        ratePerSecond: 0.016,
        unit: "",
        format: "number",
        color: "text-orange-400",
      },
      {
        id: "hiv-infections",
        label: "HIV/AIDS Infected People",
        labelTh: "ผู้ติดเชื้อ HIV/AIDS",
        baseValue: 39_400_000,
        ratePerSecond: 0,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
      {
        id: "money-spent-drugs",
        label: "Money Spent on Drugs Today",
        labelTh: "เงินใช้จ่ายยาเสพติดวันนี้",
        baseValue: 0,
        ratePerSecond: 12_731,
        unit: "$",
        format: "number",
        color: "text-purple-400",
      },
      {
        id: "cigarettes-smoked",
        label: "Cigarettes Smoked Today",
        labelTh: "สูบบุหรี่วันนี้",
        baseValue: 0,
        ratePerSecond: 190_972,
        unit: "",
        format: "number",
        color: "text-gray-400",
      },
    ],
  },
  {
    id: "water",
    title: "Water",
    titleTh: "น้ำ",
    icon: "Droplets",
    color: "text-sky-400",
    bgColor: "bg-sky-500/10 border-sky-500/20",
    stats: [
      {
        id: "water-used",
        label: "Water Used Today (liters)",
        labelTh: "น้ำที่ใช้วันนี้ (ลิตร)",
        baseValue: 0,
        ratePerSecond: 127_315,
        unit: "",
        format: "number",
        color: "text-sky-400",
      },
      {
        id: "water-no-access",
        label: "People Without Clean Water",
        labelTh: "ผู้ไม่มีน้ำสะอาดใช้",
        baseValue: 785_000_000,
        ratePerSecond: 0,
        unit: "",
        format: "number",
        color: "text-blue-400",
      },
      {
        id: "water-disease-deaths",
        label: "Deaths from Water Related Disease Today",
        labelTh: "เสียชีวิตจากโรคเกี่ยวกับน้ำวันนี้",
        baseValue: 0,
        ratePerSecond: 0.116,
        unit: "",
        format: "number",
        color: "text-red-400",
      },
    ],
  },
];
